ODSEGMENTS = {'s000': 'Total number of jobs',
              'sa01': 'Number of jobs of workers age 29 or younger',
              'sa02': 'Number of jobs for workers age 30 to 54',
              'sa03': 'Number of jobs for workers age 55 or older',
              'se01': 'Number of jobs with earnings $1250/month or less',
              'se02': 'Number of jobs with earnings $1251/month to $3333/month',
              'se03': 'Number of jobs with earnings greater than $3333/month',
              'si01': 'Number of jobs in Goods Producing industry sectors',
              'si02': 'Number of jobs in Trade, Transportation, and Utilities industry sectors',
              'si03': 'Number of jobs in All Other Services industry sectors'}
